name: Ashbane.org Bugtracker
description: >
  description: >
  Report bugs to help us improve Adhbane.org. Duplicates will be deleted. Author: zenoshi1 (discord). License: CC BY-ND 4.0 – keep author credit unchanged.
body:
  - type: input
    id: character
    attributes:
      label: Character Name
      description: Add your character name
      placeholder: e.g., Thrallius
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: game-version
    attributes:
      label: Game Version / Build Number
      description: Enter the client build number, if known (e.g. 4.3.4.15595)
      placeholder: e.g., 4.3.4.15595
    validations:
      required: false

  - type: input
    id: datetime
    attributes:
      label: Approximate Date/Time When Issue Occurred
      placeholder: e.g., 2025-04-05 14:30 Server Time
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to fill out a bug report. Remember to fill out all fields including the title above. 
        An issue that is not properly filled out (not followed this form)/duplicated will be closed.

  - type: dropdown
    id: client-type
    attributes:
      label: What client do you play on?
      options:
        - Ashbane.org Client
        - Other Server Client
    validations:
      required: true

  - type: dropdown
    id: ashbane-client
    attributes:
      label: If you selected [Ashbane.org Client], choose the version
      options:
        - .torrent client (Ashbane.org)
        - .zip client (Ashbane.org)
        - Minimal client (Ashbane.org)
    validations:
      required: false

  - type: input
    id: other-server-name
    attributes:
      label: If you selected [Other Server Client], enter the original server name
      placeholder: e.g., Firestorm, Warmane, Atlantiss
    validations:
      required: false

  - type: input
    id: other-server-link
    attributes:
      label: Link to the client download (if available)
      placeholder: https://example-server.org/download
    validations:
      required: false

  - type: checkboxes
    id: faction
    attributes:
      label: Faction
      options:
        - label: Alliance
        - label: Horde

  - type: dropdown
    id: level-bracket
    attributes:
      label: Content Phase
      options:
        - Generic
        - 1-20
        - 20-40
        - 40-60
        - 60-80
        - 80-85

  - type: dropdown
    id: severity
    attributes:
      label: Severity of the Bug
      options:
        - Critical (Game-breaking / Exploit)
        - Major (Affects gameplay significantly)
        - Moderate (Annoying but not game-breaking)
        - Minor (Cosmetic or minor inconvenience)
    validations:
      required: true

  - type: checkboxes
    id: reproducibility
    attributes:
      label: Is this issue consistently reproducible?
      options:
        - label: Yes, happens every time
        - label: Sometimes
        - label: No, it happened once

  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: |
        Describe the bug in detail. Database to link spells, NPCs, quests etc: https://www.wowhead.com/cata
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Blizzlike Behaviour
      description: |
        Describe how it should be working without the bug. Link to evidence if possible such as YouTube videos or WoWHead comments from the time.
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Source
      description: |
        HEADS UP: include sources in your bug report which are relevant to the **Cataclysm 4.3.4 (Build 15595)** game version, 
        we will close any bug like "X should be changed to Y" reported without sources.
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        Describe precisely how to reproduce the bug so we can fix it or confirm its existence:
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra Notes
      description: |
        Any information that can help the developers to identify and fix the issue should be put here.
        Examples:
        Links to items/NPCs/quests from WoWhead/YouTube etc.
        Images place
      placeholder: |
        None
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Attachments:**  
        If applicable, please include screenshots or video evidence in the comments after submitting the report. This helps us validate issues more quickly.
